apiVersion: apps/v1
kind: Deployment
metadata:
      name: myrdeployment		# ReplicationController name
spec:
     template: 				  
       metadata:
            name: mydep   # containers/pods name
            labels:
              name: dp			# label of container/pod
       spec:
         containers:
            - name: mydep
              image: httpd

     selector:
      matchLabels:
         name: dp					# selector name should be same as label of container
     replicas: 3     					 # number of replicas to create

