apiVersion: apps/v1
kind: DaemonSet
metadata:
      name: mydaemonset         # DaemonSet name
spec:
     template:
       metadata:
            name: mydaemon   # containers/pods name
            labels:
              name: ds          # label of container/pod
       spec:
         containers:
            - name: mydaemon
              image: httpd
         
         tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule        
     selector:
      matchLabels:
         name: ds                                       # selector name should be same as label of container
                                                         # number of replicas to create
