apiVersion: v1
kind: ReplicationController
metadata:
      name: replicationcon
spec:
    template:
      metadata:
         name: replication
         labels:
           name: rc
      spec:
        containers:
        - name: replication
          image: nginx
    selector:
        name: rc
    replicas: 4      
